services:
  backend:
    image: evil55/work_backend:latest
    container_name: back_blue
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=blue
      - SERVER_ENV=blue
      - SERVER_URL=localhost
    env_file:
      - .env
    networks:
      - ubuntu_app-network

  nginx_server:
    image: evil55/work_frontend:latest
    container_name: nginx_server
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /home/ubuntu/nginx.conf:/etc/nginx/conf.d/default.conf  # 올바른 파일 경로 사용
      - /home/ubuntu/service_env.inc:/etc/nginx/conf.d/service_env.inc
      - /etc/letsencrypt:/etc/letsencrypt  # SSL 인증서 볼륨
      - /var/www/certbot:/var/www/certbot  # Certbot 볼륨
    networks:
      - ubuntu_app-network

networks:
  ubuntu_app-network:
    external: true
